### ISSUE TITLE
Make strings translation ready

### ISSUE THREAD

**Issue by sakinshrestha** [ExtendStudio/mesmerize#12]
* Make following text strings translation ready
** customizer\customizer-controls.php line 242 and 243, "Section is already in page" and "Pro Only"
** customizer\js\customize.js line 106 "Close Panel", 246 'Choose Images', use {{{wp_localize_script()}}} to translate strings in js files
** customizer\SidebarGroupButtonControl.php line 66 "Close Panel"

**Comment by justintadlock** [comment]
* `inc/functions.php` - All sidebar names in `mesmerize_widgets_init()`.
* `inc/templates-functions` - 193 - "Lorem ipsum" text. (Note: I don't see where this is used in the theme.)

**Comment by justintadlock** [comment]
From `inc/general-options/colors.php`, all of the `label` values should be internationalized:

```
function mesmerize_get_default_colors()
{
    return array(
        array("label" => "Primary", "name" => "color1", "value" => "#03a9f4"),
        array("label" => "Secondary", "name" => "color2", "value" => "#ff8c00"),
        array("label" => "color3", "name" => "color3", "value" => "#fbc02d"),
        array("label" => "color4", "name" => "color4", "value" => "#8c239f"),
        array("label" => "color5", "name" => "color5", "value" => "#4caf50"),
    );
}
```

However, I don't see the labels in use in the theme anywhere.  If not using them, you should probably just remove.

Also, in that same file, this text string should be internationalized:

```
return "{$color} not found";
```
