### ISSUE TITLE
Prefixing Custom filters and custom action hooks with theme slug

### ISSUE THREAD

**Issue by sakinshrestha** [ExtendStudio/mesmerize#15]
* It is a good idea to prefix custom filters and action hooks with theme slug
* Check following for filters:
    * header_top_bar_class line 62 in inc\header-options\navigation-options\top-bar.php
    * mesmerize-copyright line 169 in inc\templates-functions.php
        * Here, use {{{mesmerize_copyright}}}, for consistency
    * the_mesmerize_pagination_navigation_markup_template line 228 inc\templates-functions.php
        * Again for consistency
    * is_shortcode_refresh inc\templates-functions.php line 299
    * Same consistency issues with mesmerize-hero-vertical-align, mesmerize-hero-content-vertical-align, mesmerize-hero-media-vertical-align
* Check following for action hooks:
    * header_top_bar_content_print line 42 inc\header-options\navigation-options\top-bar.php

**Comment by justintadlock** [comment]
Here's some other hooks I noticed without a prefix:

* `inc/functions.php` - 28 - `custom_header_args`
* `inc/functions.php` - 470 - `header_title`
* `inc/functions.php` - 664 - `footer_background_atts`
